### ISSUE TITLE
Support for Month, Quarter and Year Frequencies

### ISSUE THREAD

**Issue by mdancho84** [FBruzzesi/timebasedcv#63]
According to the documentation for `TimeBasedSplit`:

> frequency: str
>        The frequency (or time unit) of the time series. Must be one of "days", "seconds", "microseconds",
>        "milliseconds", "minutes", "hours", "weeks". These are the only valid values for the `unit` argument of
>        `timedelta` from python `datetime` standard library.

Is it possible to support time frequencies like "month", "quarter" and "year"?

**Comment by FBruzzesi** [comment]
Hey thanks for reporting this! I already have #8 open that would enable the support for these time frequencies. As I did not have a use case in my day to day I never pursued it, but definitly this is a nice incentive to do so 👌

**Comment by mdancho84** [comment]
That's fantastic. For now day is ok. In future adding month, quarter and year would be huge. Let me know if you'd like assistance. 

Amazing work. I'll also add timebasedcv to pytimetk GitHub page and website. My package is standing on your shoulders for TSCV now. Awesome. 👏
